name: my first github action
on: [push]
jobs:
   build-the-project:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '14.15.4'
         - run: node -v
 
 